sudo: false
language: ruby
rvm:
  - 2.3.1
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: your_secure_secret
  gem: active_job_log
  on:
    tags: true
    repo: platanus/active_job_log
